POST localhost:8080/update/gauge/cpu.usage.total/100.01

###
POST localhost:8080/update/counter/add.product/10

### shoud be Method Not Allowed
GET localhost:8080/update/counter/add.product/10
Accept-Encoding:

### shoud be Bad Request
POST localhost:8080/update/gauge/add.product/aa

### shoud be Bad Request
POST localhost:8080/update/gauge123/add.product/100.1

### shoud be NotFound
POST localhost:8080/update/gauge123/100.1

###
POST http://localhost:8080/update/gauge/Lookups/0.000001
Content-Type: text/plain

###
POST http://localhost:8080/update/gauge/Cut/0.000001

### Get metric value
GET localhost:8080/value/counter/add.product
Accept-Encoding:

### Not Found
GET localhost:8080/value/counter/add.product1

### get all metrics
GET localhost:8080/
Accept-Encoding: gzip

### update counter by json
POST localhost:8080/update
Content-Type: application/json

{
  "id": "add.product",
  "type": "counter",
  "delta": 10
}

### update gauge by json
POST localhost:8080/update
Content-Type: application/json

{
  "id": "cpu.usage.total",
  "type": "gauge",
  "value": 100.01
}

### get json metric by type
POST localhost:8080/value/
Content-Type: application/json

{
  "id": "cpu.usage.total",
  "type": "gauge"
}

### get json metric by type
POST localhost:8080/value/
Content-Type: application/json

{
  "id": "add.product",
  "type": "counter"
}

### update gauge by json wich compress
POST localhost:8080/update
Content-Type: application/json
Accept-Encoding: gzip

{
  "id": "cpu.usage.total",
  "type": "gauge",
  "value": 100.01
}